### ISSUE TITLE
Add more padding bt tags

### ISSUE THREAD

**Issue by floodsk** [floodsk/portfolio#12]
Environment: Interior pages
Breakpoints: 992+

Increase padding bt individual category and vertical pipe. right now it looks like 5px, can we to 10px?
![screen shot 2017-11-04 at 4 39 51 pm](https://user-images.githubusercontent.com/8250742/32409734-3a2639a0-c17f-11e7-8171-bd1a1a914c41.png)

**Comment by kylecarter** [comment]
@floodsk This has been addressed.

#### FYI:
Using the terminal app do the following:
* Type `cd ` with the path to where you downloaded the portfolio repo. No worries if you don't know it if you find the repo in the finder app you can drag the folder named portfolio into the terminal app and it will place the path info for you. **NOTE**: Remember to type `cd` + a space character.
* Hit enter when you have done the above.
* You can now run the `git pull origin master command` to get the latest changes.
* When `git pull` is done you can then run `php -S localhost:8080` to start a PHP development server.
* You should now be able to enter `localhost:8080` in a browser URL bar and see your local website running.
* Type `ctrl + c` in the terminal where you ran the `php -S localhost:8080` when you are done this will deactivate the development server.
