### ISSUE TITLE
Title/Tag/Main Copy Alignment

### ISSUE THREAD

**Issue by floodsk** [floodsk/portfolio#4]
On the interior pages, the title and tags should be aligned to the body copy. Im seeing this across breakboints
![interior page - alignment mobile](https://user-images.githubusercontent.com/8250742/32395954-558597be-c0b1-11e7-8b78-2dc0be59048a.png)
![interior page - alignment](https://user-images.githubusercontent.com/8250742/32395955-55977b32-c0b1-11e7-9867-d52014101ff1.png)

**Comment by kylecarter** [comment]
@floodsk This has been addressed.

#### FYI:
Using the terminal app do the following:
* Type `cd ` with the path to where you downloaded the portfolio repo. No worries if you don't know it if you find the repo in the finder app you can drag the folder named portfolio into the terminal app and it will place the path info for you. **NOTE**: Remember to type `cd` + a space character.
* Hit enter when you have done the above.
* You can now run the `git pull origin master command` to get the latest changes.
* When `git pull` is done you can then run `php -S localhost:8080` to start a PHP development server.
* You should now be able to enter `localhost:8080` in a browser URL bar and see your local website running.
* Type `ctrl + c` in the terminal where you ran the `php -S localhost:8080` when you are done this will deactivate the development server.
