### ISSUE TITLE
Title text alignment/line breaks

### ISSUE THREAD

**Issue by floodsk** [floodsk/portfolio#5]
1) On the homepage the categories text should be left aligned. 

2) Also can we widen their columns to maybe a min of 75px (not sure what % that would be) - mostly just want to avoid text wrapping with shorter titles (eg. "about me" should take one line" "user experience design" take up 2, not three lines. 

3) long category names overlap page titles
 
Affecting laptop and larger browser-widths.

![homepage - title](https://user-images.githubusercontent.com/8250742/32396343-c9c955e2-c0b2-11e7-9a27-9d4a62c9f9c8.png)

**Comment by kylecarter** [comment]
@floodsk This has been addressed.

#### FYI:
Using the terminal app do the following:
* Type `cd ` with the path to where you downloaded the portfolio repo. No worries if you don't know it if you find the repo in the finder app you can drag the folder named portfolio into the terminal app and it will place the path info for you. **NOTE**: Remember to type `cd` + a space character.
* Hit enter when you have done the above.
* You can now run the `git pull origin master command` to get the latest changes.
* When `git pull` is done you can then run `php -S localhost:8080` to start a PHP development server.
* You should now be able to enter `localhost:8080` in a browser URL bar and see your local website running.
* Type `ctrl + c` in the terminal where you ran the `php -S localhost:8080` when you are done this will deactivate the development server.
