### ISSUE TITLE
Images stretched out

### ISSUE THREAD

**Issue by floodsk** [floodsk/portfolio#8]
Environment: Interior Pages
Breakpoints : All

Images are not displaying correctly, see attached
![interior page image](https://user-images.githubusercontent.com/8250742/32409365-6424f388-c178-11e7-9939-a0543c6cedd0.png)
.

**Comment by kylecarter** [comment]
@floodsk This has been addressed.

#### FYI:
Using the terminal app do the following:
* Type `cd ` with the path to where you downloaded the portfolio repo. No worries if you don't know it if you find the repo in the finder app you can drag the folder named portfolio into the terminal app and it will place the path info for you. **NOTE**: Remember to type `cd` + a space character.
* Hit enter when you have done the above.
* You can now run the `git pull origin master command` to get the latest changes.
* When `git pull` is done you can then run `php -S localhost:8080` to start a PHP development server.
* You should now be able to enter `localhost:8080` in a browser URL bar and see your local website running.
* Type `ctrl + c` in the terminal where you ran the `php -S localhost:8080` when you are done this will deactivate the development server.

**Comment by kylecarter** [comment]
### As an additional note
When uploading media to post content using the the add media button, select the Full Size - Size option. This tells Wordpress to use the actual image size when adding it to pages.
